cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ccl722:
      email: qscft88@gmail.com
      name: EddieCLCheng
      password: $2b$12$BZLSIOkHDHQHy89Bpo6HXOiBkCelpJENEp2s/y846cbZJdrka8KR6
    dbaldwin:
      email: dbaldwin@gmail.com
      name: David Baldwin
      password: $2b$12$E9/bCaN/r8sN/FV2l8NpgOgspUBAp7UAVU6BgsXJzp/pW8gQWCprC
preauthorized:
  emails:
  - melsby@gmail.com
